"""Merges workflow-generated ingredient entries into
_buildSupplementaryIngredients, deduping with the same baseKey logic the
Dart service uses (first 3 words >1 char, last word depluralized).

Usage: python tools/merge_ingredients.py <entries.json>
entries.json: {"entries": [{"name","category","keywords"}, ...]}
"""
import json
import re
import sys
from collections import defaultdict

SERVICE = 'lib/services/ingredient_suggestion_service.dart'
USDA = 'assets/data/common_ingredients.json'

CATS = ['Bakery','Baking','Beverages','Breakfast','Canned & Jarred','Condiments',
        'Dairy','Frozen','Grains & Pasta','Household','International','Meat',
        'Oils & Vinegars','Personal Care','Produce','Seafood','Snacks',
        'Spices & Seasonings']


def depluralize(w):
    if w.endswith('ies') and len(w) > 4:
        return w[:-3] + 'y'
    if w.endswith('es') and len(w) > 3:
        return w[:-2]
    if w.endswith('s') and len(w) > 3 and not w.endswith('ss'):
        return w[:-1]
    return w


def base_key(name):
    words = [w for w in re.split(r'\s+', name.lower()) if len(w) > 1][:3]
    if not words:
        return name.lower()
    words[-1] = depluralize(words[-1])
    return ' '.join(words)


# Existing keys: USDA descriptions + current supplementary names
existing = set()
for e in json.load(open(USDA, encoding='utf-8')):
    existing.add(base_key(e['description']))
src = open(SERVICE, encoding='utf-8').read()
body = src.split('_buildSupplementaryIngredients()')[-1]
pat = re.compile(r"\(\s*'((?:[^'\\]|\\.)*)'\s*,\s*'([^']*)'\s*,\s*(?:'(?:[^'\\]|\\.)*'|null)\s*\)")
for m in pat.findall(body):
    existing.add(base_key(m[0].replace("\\'", "'")))

entries = json.load(open(sys.argv[1], encoding='utf-8'))['entries']
print(f'candidates: {len(entries)}')

merged, seen_new = [], set()
skipped_dup, skipped_cat = 0, 0
for e in entries:
    name = e['name'].strip()
    cat = e['category'].strip()
    kw = re.sub(r'\s+', ' ', e['keywords'].strip().lower())
    if cat not in CATS:
        skipped_cat += 1
        continue
    k = base_key(name)
    if k in existing or k in seen_new:
        skipped_dup += 1
        continue
    seen_new.add(k)
    merged.append((name, cat, kw))

print(f'new unique: {len(merged)}  (dups skipped: {skipped_dup}, bad cat: {skipped_cat})')

# Group by category, emit Dart tuples
by_cat = defaultdict(list)
for name, cat, kw in merged:
    by_cat[cat].append((name, kw))


def dart_str(s):
    return "'" + s.replace("\\", "\\\\").replace("'", "\\'") + "'"


lines = ['', '      // ════ EXPANSION: comprehensive coverage (autogenerated audit) ════']
for cat in CATS:
    items = sorted(by_cat.get(cat, []))
    if not items:
        continue
    lines.append(f'      // ── {cat.upper()} (expansion) ──')
    for name, kw in items:
        lines.append(f'      ({dart_str(name)}, {dart_str(cat)}, {dart_str(kw)}),')
block = '\n'.join(lines) + '\n'

anchor = "      ('Deodorant', 'Personal Care', 'deodorant antiperspirant'),\n    ];"
if anchor not in src:
    print('ERROR: insertion anchor not found')
    sys.exit(1)
src = src.replace(anchor, "      ('Deodorant', 'Personal Care', 'deodorant antiperspirant'),\n" + block + '    ];')
open(SERVICE, 'w', encoding='utf-8').write(src)
print('inserted', len(merged), 'entries into', SERVICE)
